- keymap.h
- mainwindow.cpp
- qtkeypadbridge.cpp
- Reimplemented the keymap, mapping all the keys to as intuitive key combinations as I could think of, while also preserving the existing Alt combinations. (Some of the Alt combinations were and still aren't working on windows due to collision with application menu and duplication)
- Reimplemented keypad key look-up to be O(1) instead of O(n)
> Keypad Keymap improvement and inclusion of more intuitive key combinations

- qtkeypadbridge.cpp
Makes "Alt + Shift + " key combinations possible.
There is a catch though. If you press Shift before Alt, it's going to release the Shift which is interpreted by calc as some type of "one time shift lock". So:
Shift + 9 = Shift + (
Shift + Alt + 9 = [Shift is released, but maybe on one-time-lock] + (
Alt + Shift + 9 = (
I don't know if nspire-io exhibits the same behavior, but it is something to keep in mind when testing.
> Alt prevents or releases Shift

- firebird.pro
To avoid crashing on x86_64 Archlinux distros. Looks like it's enabled by default.
> Forced PIE disabling for Archlinux

- config.tests/-no-pie/test.c
- config.tests/-no-pie/test.pro
- firebird.pro
This seems to be the proper qmake way to do it. It should now work on PIE-default toolchains, as well as older versions of GCC that don't have the -no-pie flag.
> Check for -no-pie linker flag, and use it if available

- README.md
This commit fixes a rendering issue for github.com by adding a space after the #'s on one of the headers.
> Fix Readme Markdown

- qmlbridge.cpp
In particular, this solves a crash on iOS arm64 (at least with ASan, since it detects a stack buffer overflow: https://www.irccloud.com/pastebin/kzGtT07x/)
> Use QFileInfo's basename for QMLBridge::basename

- core/translate_arm.cpp
- firebird.pro
Needs a confirmation on other platforms that using `+=` instead of `=` does not introduce regressions.
> Fix building with android-clang

- main.cpp
Necessary to make it work properly on non-Plasma DEs, #148.
Needs verification on macOS and iOS which have their own scaling options.
> Set the EnableHiDPIScaling attribute

- core/coproc.cpp
- core/debug.cpp
- core/debug.h
- core/emu.cpp
- core/mmu.c
The translation table was never loaded after resume as the speed hack prevented that.
Also found an unused variable and removed it.
> Fix resume if PC in SRAM and SUPPORT_LINUX disabled

- firebird.pro
- Resulted in "-fPIC -fno-pie" beforehand, which results in broken code
causing "signal not found" when built with GCC
Added support for `-nopie` to support LLVM 4.
> Use only -no-pie/-nopie instead of combining it with -fno-pie

- firebird.pro
- Disabling LTO for just the UI does not seem to work with qmake, so just
disable it completely with clang.
Depends on #167
> Don't use LTO with clang

- core/cpu.cpp
- core/emu.cpp
- core/emu.h
- emscripten/Makefile
- emscripten/main.cpp
- emuthread.cpp
- firebird.pro
Builds against NDK r21 and Qt 5.14.1 for armeabi-v7a and arm64-v8a now.
I was surprised that clang as provided by the NDK doesn't understand the `@PAGE` syntax needed for clang for iOS, maybe that changed in a newer llvm version?
> Various cleanups, preparations for updated android support

- android/AndroidManifest.xml
- android/build.gradle
- android/res/values/libs.xml
- core/asmcode_aarch64.S
- core/asmcode_arm.S
- core/os/os-android.cpp
- core/os/os-linux.c
- core/translate_aarch64.cpp
- core/usblink.c
- firebird.pro
- qml/Firebird/UIComponents/FileSelect.qml
- qmlbridge.cpp
- qmlbridge.h
Like #94, but uses the now native support in Qt 5.13.
Unfortunately it does not support creation of files, so only existing files can be written.
~Needs some testing, here's an APK: [firebird.zip](https://github.com/nspire-emus/firebird/files/3326263/firebird.zip)~
Depends on #184
> Support native Android file picker used by Qt >= 5.13

- core/debug.cpp
- core/gdbstub.c
Using close for sockets on MinGW is not possible, it generated an error
message and the socket was left open.
Now restarting works without errors on Windows. Both rdbg and gdb still work on Linux, even after restarting.
> Close sockets on MinGW properly, use -1 consistently

- firebird.pro
As discussed in #227 
This works around an Qt bug on both FreeBSD and Linux with clang having LTO enabled.
> FreeBSD LTO and linker patch

- android/AndroidManifest.xml
- core/os/os-android.cpp
- core/usblink.c
- core/usblink_cx2.cpp
- mainwindow.cpp
- qml/ConfigPageDebug.qml
- qml/ConfigPageFileTransfer.qml
- qml/ConfigPageKits.qml
- qml/Firebird/UIComponents/KitList.qml
- qml/MobileUIConfig.qml
- qmlbridge.cpp
- qmlbridge.h
Mixture of all kinds of changes.
See the individual commits for details.
> Various fixes mostly for the mobile version

- core/gdbstub.c
The socket is set nonblocking unconditionally, so the missing code for polling
made it close the connection prematurely.
Fixes #259
> Implement WinSock2 polling in gdbstub

- qml/Keypad.qml
- qml/MobileUIFront.qml
- qml/NDualButton.qml
Most importantly this PR addresses #41, which I was finally able to reproduce on my new phone and on desktop by setting `QT_FONT_DPI=400` (bigger -> more extreme). Beyond that some smaller inconsistencies and graphical issues are fixed. (Spot the changes! :P)
<table>
<tr><th width="50%">Before</th><th width="50%">After</th></tr>
<tr><td colspan="2" align="center">Linux desktop</td></tr>
<tr><td><img src="https://user-images.githubusercontent.com/1622084/197032525-36c8dcd9-c7e5-4d1c-be78-241a8ac1995e.png"/></td><td><img src="https://user-images.githubusercontent.com/1622084/197032734-c5e54fe5-f4c3-4231-96f3-14282b9acbb9.png"/></td></tr>
<tr><td colspan="2" align="center">Linux desktop with QT_FONT_DPI=400 (#41)</td></tr>
<tr><td><img …
> Keypad improvements

- TODO.md
- core/cpu.cpp
- core/cpu.h
- core/cx2.cpp
- core/emu.cpp
- core/emu.h
- core/keypad.cpp
- core/misc.c
The On button has different behaviour. On the CX II, sleep mode had to be implemented to even allow turning it off and on.
> Fix PTT for CX and CX II

- .github/workflows/android.yml
> Add GitHub workflow for Android

- qml/Keypad.qml
- qml/NButton.qml
- qtkeypadbridge.cpp
Otherwise it's possible that the key is stuck because the KeyRelease event is not received.
Needs some practical testing to check whether this breaks something.
> Release pressed keys on FocusOut events

- core/debug.cpp
- core/gdbstub.c
Otherwise any possible child processes inherit those and keep the ports busy.
> Set FD_CLOEXEC on sockets

- core/emu.cpp
Is the text clear enough?
Much easier to implement this in the core, but unfortunately that means it's not translatable.
> Warn if an incomplete CX II bootrom is used

- mainwindow.cpp
The alternative is switching to `QQuickView`, but that's IMO rather risky and I could already hit some weird behaviour with basic testing.
> Allow touch events in the keypad widget (#292)

- .github/workflows/android.yml
Using the default/latest version broke, see the added comment for details.
It's probably a good idea to pin to a specific version anyway.
Fixes #303
> Use SDK 32 explicitly in the android build action

- .github/workflows/android.yml
- android/build.gradle
- android/gradle/wrapper/gradle-wrapper.properties
Previously only JDK 8 was supported, meanwhile a newer version is required.
> Use JDK 17 in the Android CI build

- .github/workflows/android.yml
- .github/workflows/macOS.yml
- .github/workflows/windows.yml
Needed to fix macOS build with `setup-python: false`.
> CI: Move install-qt-action from v3 to v4 and disable setup-python: false for now

- qtkeypadbridge.cpp
> Use scancode from key event for mapping release events to the keypad

- core/debug.cpp
- core/usblink.c
- core/usblink.h
- core/usblink_queue.cpp
- core/usblink_queue.h
- mainwindow.cpp
- mainwindow.ui
- qml/ConfigPageFileTransfer.qml
- qmlbridge.cpp
- qmlbridge.h
- usblinktreewidget.cpp
Some refactoring to allow simple file creation using `usblink_put_file` + a button to create the file.
Fixes #343
Desktop UI:
Mobile UI:
> Add button to leave Press-to-Test mode

- core/os/os-android.cpp
- core/os/os.h
- qml/Firebird/UIComponents/FileSelect.qml
- qmlbridge.cpp
Use the ContentResolver API to get the display name for content: URIs.
Remaining TODO: Add refreshing to other uses of Emu.basename as well.
Now I can send "crä fti.tns" using the mobile UI and even flash filenames like "fläsh file 🤣" are displayed properly.
> [Android] Properly get the basename of files
